<a href="https://colab.research.google.com/github/sebakrys/data-science-bootcamp-A-Z/blob/main/22_s7_metryki_klasyfikacji.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import numpy as np

import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

# Metryki - klasyfikacja binarna
Accuracy

In [56]:
y_true = np.array([1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1])
y_pred = np.array([1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1])

In [57]:
from sklearn.metrics import accuracy_score

accuracy_score(y_true, y_pred)

0.9

In [58]:
results = pd.DataFrame({'y_true':y_true, 'y_pred': y_pred})
results

    y_true  y_pred
0        1       1
1        0       0
2        1       1
3        1       1
4        0       0
5        1       1
6        0       0
7        0       0
8        0       1
9        1       1
10       1       0
11       0       1
12       1       1
13       1       1
14       0       0
15       1       1
16       1       1
17       0       0
18       0       0
19       1       1
20       1       1
21       1       1
22       0       0
23       1       1
24       1       1
25       0       0
26       1       1
27       1       1
28       0       0
29       1       1

In [59]:
results = results.sort_values(by='y_true')
results = results.reset_index(drop=True)
results['sample'] = results.index + 1
results

    y_true  y_pred  sample
0        0       0       1
1        0       0       2
2        0       0       3
3        0       1       4
4        0       0       5
5        0       1       6
6        0       0       7
7        0       0       8
8        0       0       9
9        0       0      10
10       0       0      11
11       0       0      12
12       1       1      13
13       1       1      14
14       1       1      15
15       1       1      16
16       1       1      17
17       1       1      18
18       1       1      19
19       1       1      20
20       1       1      21
21       1       1      22
22       1       1      23
23       1       0      24
24       1       1      25
25       1       1      26
26       1       1      27
27       1       1      28
28       1       1      29
29       1       1      30

In [60]:
fig = make_subplots(rows=2, cols=1)
fig.add_trace(go.Scatter(x=results['sample'], y=results['y_true'], mode='markers', name='y_true'), row=1, col=1)
fig.add_trace(go.Scatter(x=results['sample'], y=results['y_pred'], mode='markers', name='y_pred'), row=2, col=1)

## Confussion matrix

In [61]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_true, y_pred)
cm

array([[10,  2],
       [ 1, 17]])

In [62]:
import plotly.figure_factory as ff


def plot_confusion_matrix(cm):
  cm = cm[::-1]
  cm = pd.DataFrame(cm, columns=['pred_0', 'pred_1'], index=['true_1', 'true_0'])

  fig = ff.create_annotated_heatmap(z=cm.values, x=list(cm.columns), y=list(cm.index), colorscale='ice', showscale=True, reversescale=True)
  fig.update_layout(width=500, height=500, title='Confusion Matrix', font_size=16)
  fig.show()

plot_confusion_matrix(cm)

In [63]:
tn, fp, fn, tp = cm.ravel()#true-negative, false-positive, false-negative, true-positive
print(tn, fp, fn, tp)

10 2 1 17

### Type 1 error - False Positive rate

In [64]:
fpr = fp/(fp+tn)
fpr

0.16666666666666666

### Type 2 error - False Negative rate

In [65]:
fnr = fn/(fn+tp)
fnr

0.05555555555555555

###Presission
ile obserwacji przewidywanych jako pozytywne sa w rzeczywistosci pozytywne

In [66]:
precision = tp/(tp+fp)
precision

0.8947368421052632

#Recall
jak wiele obserwacji z wszystkich pozytywnych sklasyfikowalismy jako pozytywne

In [67]:
recall = tp/(tp+fn)
recall

0.9444444444444444

#Krzywa ROC

In [70]:
from sklearn.metrics import roc_curve


fpr, tpr, tresh =  roc_curve(y_true, y_pred, pos_label=1)
roc = pd.DataFrame({'fpr':fpr, 'tpr':tpr})
roc

        fpr       tpr
0  0.000000  0.000000
1  0.166667  0.944444
2  1.000000  1.000000

In [71]:
def plot_roc_curve(y_true, y_pred):
    # Binary classification
    from sklearn.metrics import roc_curve
    fpr, tpr, tresh = roc_curve(y_true, y_pred, pos_label=1)

    fig = go.Figure(data=[go.Scatter(x=roc['fpr'], y=roc['tpr'], line_color='red', name='ROC Curve'),
                        go.Scatter(x=[0, 1], y=[0, 1], mode='lines', line_dash='dash', line_color='navy')],
                    layout=go.Layout(xaxis_title='False Positive Rate',
                                    yaxis_title='True Positive Rate',
                                    title='ROC Curve',
                                    showlegend=False,
                                    width=800,
                                    height=400))
    fig.show()
plot_roc_curve(y_true, y_pred)

#Metryki klasyfikacja wieloklasowa

In [78]:

y_true = np.array([1, 0, 1, 2, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2])
y_pred = np.array([0, 0, 1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 1, 1, 1, 2, 2])


accuracy_score(y_true, y_pred)

0.7241379310344828

In [80]:
cm = confusion_matrix(y_true, y_pred)
cm

array([[ 6,  1,  0],
       [ 3, 10,  2],
       [ 0,  2,  5]])

In [82]:
def plot_confusion_matrix(cm):
    cm = cm[::-1]
    cm = pd.DataFrame(cm, columns=['pred_0', 'pred_1', 'pred_2'], index=['true_2','true_1', 'true_0'])

    fig = ff.create_annotated_heatmap(z=cm.values, x=list(cm.columns), y=list(cm.index),
                                      colorscale='ice', showscale=True, reversescale=True)
    fig.update_layout(width=400, height=400, title='Confusion Matrix', font_size=16)
    fig.show()

plot_confusion_matrix(cm)

## Raport Klasyfikacji

In [83]:
from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.67      0.86      0.75         7
           1       0.77      0.67      0.71        15
           2       0.71      0.71      0.71         7

    accuracy                           0.72        29
   macro avg       0.72      0.75      0.73        29
weighted avg       0.73      0.72      0.72        29

In [84]:
print(classification_report(y_true, y_pred, target_names=['label_1', 'label_2', 'label_3']))

              precision    recall  f1-score   support

     label_1       0.67      0.86      0.75         7
     label_2       0.77      0.67      0.71        15
     label_3       0.71      0.71      0.71         7

    accuracy                           0.72        29
   macro avg       0.72      0.75      0.73        29
weighted avg       0.73      0.72      0.72        29